apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-practice-deployment
  namespace: gimbooks
  labels:
    app: drf-practice
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: drf-practice
  template:
    metadata:
      labels:
        app: drf-practice
    spec:
      containers:
        - name: drf-practice
          image: amangimbooks/drf-practice:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: drf-practice-config
                  key: DJANGO_DEBUG
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: drf-practice-secret
                  key: SECRET_KEY
